apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: unpod

resources:
  - voice-executor.yaml

commonLabels:
  app.kubernetes.io/part-of: unpod
  app.kubernetes.io/component: voice

images:
  - name: unpod-voice-executor
    newName: PLACEHOLDER_ECR/unpod-voice-executor
    newTag: latest
