# Generated by `make deploy` from .env — do not commit secrets.
# Chart: grafana/k8s-monitoring (v4+) → Grafana Alloy → Grafana Cloud

cluster:
  name: ${CLUSTER_NAME}

destinations:
  grafana-cloud-metrics:
    type: prometheus
    url: ${GRAFANA_CLOUD_METRICS_URL}
    auth:
      type: basic
      username: "${GRAFANA_CLOUD_METRICS_USER}"
      password: "${GRAFANA_CLOUD_TOKEN}"

  grafana-cloud-logs:
    type: loki
    url: ${GRAFANA_CLOUD_LOGS_URL}
    auth:
      type: basic
      username: "${GRAFANA_CLOUD_LOGS_USER}"
      password: "${GRAFANA_CLOUD_TOKEN}"

  grafana-cloud-otlp:
    type: otlp
    url: ${GRAFANA_CLOUD_OTLP_URL}
    protocol: http
    auth:
      type: basic
      username: "${GRAFANA_CLOUD_OTLP_INSTANCE_ID}"
      password: "${GRAFANA_CLOUD_TOKEN}"
    metrics:
      enabled: true
    logs:
      enabled: true
    traces:
      enabled: true

# --- Cluster / node telemetry ---
clusterMetrics:
  enabled: true
  collector: alloy-metrics

hostMetrics:
  enabled: true
  collector: alloy-metrics
  linuxHosts:
    enabled: true
  energyMetrics:
    enabled: false

costMetrics:
  enabled: false

clusterEvents:
  enabled: true
  collector: alloy-singleton

# Pod stdout/stderr → Loki (librechat, postgres, redis, mongo, …)
podLogsViaLoki:
  enabled: true
  collector: alloy-logs

# Scrape Pods/Services with prometheus.io/scrape=true annotations
annotationAutodiscovery:
  enabled: true
  collector: alloy-metrics

# In-cluster OTLP receiver for LibreChat / other apps
applicationObservability:
  enabled: true
  collector: alloy-receiver
  receivers:
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318
    zipkin:
      enabled: false

telemetryServices:
  kube-state-metrics:
    deploy: true
  node-exporter:
    deploy: true
    # Skip eksctl System-NodeGroup (t4g.small) — only ~11 pods/node; DaemonSets fill them.
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: role
                  operator: NotIn
                  values: [system]
  kepler:
    deploy: false
  opencost:
    deploy: false

collectors:
  alloy-metrics:
    presets: [clustered, statefulset]
  alloy-logs:
    presets: [filesystem-log-reader, daemonset]
    # DaemonSet needs 1 pod per node; system t4g.small hits "Too many pods" quickly.
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: role
                  operator: NotIn
                  values: [system]
  alloy-singleton:
    presets: [singleton]
  alloy-receiver:
    presets: [deployment]
