apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: unpod

resources:
  - namespace.yaml
  - configmap.yaml
  - backend-core.yaml
  - api-services.yaml
  - web.yaml
  - centrifugo.yaml
  # ingress.yaml is rendered from ingress.yaml.tpl by `make deploy-platform`

commonLabels:
  app.kubernetes.io/part-of: unpod
